<a href="https://colab.research.google.com/github/prince2004coder/vmc-classes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

#alias name.function [use]

In [7]:
a = np.array([1,2,3,4,5,'6'])
print(a)
a = np.array([1,2,3,4,5,6])
print(a)
a = np.array([1,2,3,4,5,'hello'])
print(a)

['1' '2' '3' '4' '5' '6']
[1 2 3 4 5 6]
['1' '2' '3' '4' '5' 'hello']


In [18]:
np_arr = np.array([1,2,3.3,'hello',5,False])
print(bool(np_arr[-1]))

b = False
print(bool(b))

np_arr = np.array([1,2,3.3,'hello',5,False])
print(np_arr)


a='prince'
print(bool(a))# string mai value hai toh voh true degaa and empty, no value 0 as false

a='0'
print(bool(a))
a=0
print(bool(a))



True
False
['1' '2' '3.3' 'hello' '5' 'False']
True
True
False


In [34]:
a = np.zeros((2,4,3), dtype=int)
print(a)

print(type(a[0, 0, 0]))

a = np.ones((2,4,3), dtype=int)
print(a)

a = np.empty(3, dtype=int)# it gives 3 random values from garbage
print(a)

a = np.full(2,4,dtype=int)
print(a)



[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
<class 'numpy.int64'>
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
[0 0 0]
[4 4]


In [46]:

a = np.arange(0, 2, 4)#
print(a)


b = np.linspace(0, 2,3)
print(b)


b = np.linspace(0, 2,3,dtype=int)
print(b)

[0]
[0. 1. 2.]
[0 1 2]


In [58]:
b = np.shape([[1,2],[3,4]])
print(b)


b = np.size([[1,2],[3,4],[3,4]])
print(b)

a = np.arange(0, 2, 4)
print(a.shape)

a = np.linspace(0, 2, 4)
print(a.size)




(2, 2)
6
(1,)
4


In [91]:
a=np.random.randint(1, 10,9)
print(a)


a = [2,3,4]
a = np.random.choice(a)
print(a)

[6 6 5 8 4]


In [93]:

#a = np.array([[1,2,3,4],[5,6,7,8]])

b = a.transpose()
print(b)

a = np.random.randint([[1,2,3,4],[5,6,7,8]])

b = a.concatenate()
print(b)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


AttributeError: 'numpy.ndarray' object has no attribute 'concatenate'

In [101]:
a = np.random.randint(2,15,5)
b = np.random.randint(1,19,5)

print(np.transpose((a,b),))




a = np.random.randint(2,15,5)
b = np.random.randint(1,19,5)

print(np.concatenate((a,b),))

[[ 5  8]
 [ 5 10]
 [ 4  2]
 [11  6]
 [12 15]]
[ 6 12  9 13 11 13  5  2  7 16]


In [104]:
a = np.random.randint(2,15,5)
b = np.random.randint(1,19,5)
print(a)
print(b)
c = np.where(b > 2,b, a)
print(c)

[ 8  8 13  7  3]
[12 11 15  1 10]
[12 11 15  7 10]


In [109]:
#virat = np.array([200,250,340,420,69])


scores = []
days = ['mon', 'tue','wed' ]



for i in range(3):
  x= input(f'give the input for the {days[i]}:')




give the input for the mon:45
give the input for the tue:45
give the input for the wed:45


In [110]:
a = np.array([3,3,3,3])


b=a
b[0]= 1
print(a,b)

[1 3 3 3] [1 3 3 3]
